# Generated by Django 4.1.7 on 2023-02-16 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('GroupGuid', models.UUIDField()),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(blank=True, max_length=600)),
                ('Link', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'UserRoles',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('UserGuid', models.UUIDField()),
                ('Name', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateField()),
                ('Login', models.CharField(max_length=100)),
                ('PasswordHash', models.CharField(max_length=500)),
                ('RoleId', models.ForeignKey(db_column='RoleId', on_delete=django.db.models.deletion.DO_NOTHING, to='pai.userroles')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('GroupId', models.ForeignKey(db_column='GroupId', on_delete=django.db.models.deletion.DO_NOTHING, to='pai.groups')),
                ('UserId', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.DO_NOTHING, to='pai.users')),
            ],
            options={
                'db_table': 'UserGroups',
            },
        ),
    ]
